window.oetWords = [
  "bitter taste",
  "software developer",
  "stroke",
  "watery",
  "tumour markers",
  "abdominal area",
  "presentation",
  "wedding",
  "numbness",
  "sleep apnoea",
  "lymph nodes",
  "irritable bowel syndrome",
  "multiple sclerosis",
  "muscle dystrophy",
  "chubby",
  "menopause",
  "sprain ankle",
  "hand cream",
  "ointment",
  "swollen tongue",
  "environmental engineering",
  "skin rashes",
  "stomach cramps",
  "dyspepsia",
  "tennis ball",
  "strangulation",
  "Down syndrome",
  "yoga",
  "hiking",
  "blurred vision",
  "PPI",
  "flat position",
  "iron deficiency anaemia",
  "wheezing",
  "graphic designer",
  "shingles",
  "dust",
  "psoriasis",
  "urinary tract infection",
  "paralysis",
  "personal trainer",
  "crowded places",
  "sticky",
  "greasy",
  "bloating",
  "bouts of vomiting",
  "life-threatening",
  "finances",
  "pneumonia",
  "surveyor",
  "fertility",
  "probiotic",
  "cystitis",
  "acoustic neuroma",
  "radiation",
  "basketball",
  "market research",
  "badly taste",
  "bad odour",
  "throbbing",
  "sharp",
  "punctured lung",
  "stiffness",
  "nosebleeds",
  "appendectomy",
  "van driver",
  "sinus inflammation",
  "scarlet fever",
  "university lecturer",
  "lower back",
  "fertility treatment",
  "thirsty",
  "drowsy",
  "migraines",
  "popping sound",
  "oesophageal cancer",
  "gluten-free",
  "obese",
  "shower gels",
  "thighs",
  "fine",
  "back",
  "colouring",
  "red meat",
  "chickenpox",
  "nasal spray",
  "immune system",
  "aching",
  "programmer",
  "calamine lotion",
  "itchy",
  "eyebrows",
  "herbal oil",
  "deodorant",
  "burning",
  "iron deficiency",
  "depression",
  "weight gain",
  "heparin injection",
  "Hearing loss",
  "Impaction",
  "engineer",
  "Building sites",
  "Blotches",
  "Scalp",
  "Swelling",
  "Eczema",
  "Constipation",
  "Heel",
  "Osteoarthritis",
  "Atrial fibrillation",
  "Translator",
  "Bruising",
  "Sway",
  "Disorientation",
  "Emotional outbursts",
  "Choking",
  "Autism",
  "Holter monitor",
  "Muscle biopsy",
  "Blood thinners",
  "Unsaturated fats",
  "Dizzy spells",
  "Palpitations",
  "Breathless",
  "Bereavement",
  "Dancing instructor",
  "Died",
  "Ear infection",
  "Ablation",
  "Flu",
  "Alzheimer's disease",
  "Rods",
  "Jump",
  "Vitamin D",
  "Shoulders",
  "Fatigue",
  "Anxious",
  "Journalist",
  "Goalkeeper",
  "Tea",
  "Chef",
  "Insomnia",
  "Tomatoes",
  "Lying down",
  "Antihistamines",
  "Central nervous system",
  "Compartment syndrome",
  "Carpenter",
  "Tingling",
  "Collarbone",
  "Acupuncture",
  "Left calf",
  "Varicose veins",
  "Wrist brace",
  "Metal rod",
  "Bent",
  "Strawberry tongue",
  "Irritable",
  "Washing hair",
  "Sepsis",
  "Diabetes",
  "Knife and fork",
  "Bloodshot",
  "Fingertips",
  "Cracked lips",
  "Japan",
  "Epilepsy",
  "Concentrate",
  "Booster injection",
  "Febrile convulsion",
  "Pressure sores",
  "Physiotherapy",
  "Events manager",
  "Change dressing",
  "Judge distance",
  "Administrator",
  "Preventer",
  "Steroid",
  "Menstruation",
  "Car accident",
  "Fuzzy",
  "Injection",
  "Lunch time",
  "Swallow",
  "Vocabulary",
  "Vascular",
  "Eating",
  "Some sort of food",
  "Urinalysis",
  "Deafness",
  "Magazine editor",
  "Lethargic",
  "Visual perception",
  "Heartbeats",
  "Tightness",
  "Financial problems",
  "Cut two fingers",
  "Nausea",
  "Lung expansion",
  "Tantrum",
  "Groin area",
  "Asking",
  "Indigestion",
  "Full blood count",
  "Cloudy",
  "Cold compress",
  "Confidence",
  "Popping",
  "Clicking",
  "Deep vein thrombosis",
  "Swollen",
  "Aerobic exercises",
  "Physiotherapy session",
  "Calf calves",
  "Crutches",
  "Mouth ulcers",
  "Infection",
  "Painkillers",
  "Antisocial",
  "Chills",
  "B12 deficiency",
  "Angina",
  "Rib cage",
  "Ribcage",
  "Swallowing",
  "Drained",
  "Confusion",
  "Shivering",
  "Stinging",
  "Tonsillectomy",
  "Potassium level",
  "Overactive thyroid",
  "Gymnastics",
  "Anaemia",
  "Indoor exercises",
  "Tongue-tie",
  "Crusty mucus",
  "White crusts",
  "Antihistamine",
  "Infertile",
  "Night sweats",
  "Lying flat",
  "Clockwise",
  "Social gatherings",
  "Tinnitus",
  "Vomited",
  "Stomach",
  "Groin",
  "Gastric bypass",
  "In concentration",
  "Baggage",
  "Tailor",
  "Tendon",
  "Savoury snacks",
  "Darker",
  "Bladder",
  "Tonsillitis",
  "Dragging",
  "Corticosteroids",
  "Spider",
  "Whooping cough",
  "Scrotum",
  "Whiplash injury",
  "Pituitary",
  "Pleurisy",
  "Construction worker",
  "Pulsing",
  "Bruise",
  "Red spots",
  "Dry mouth",
  "Distracted",
  "Ginseng supplements",
  "Senna tablets",
  "Neighbour",
  "Incontinence",
  "Burping",
  "Sales manager",
  "Pre-eclampsia",
  "Four months",
  "Meat",
  "Oranges",
  "Lemonades",
  "Smoking",
  "Vegetarian",
  "Intermittent",
  "Blurred",
  "Financial difficulties",
  "Driving",
  "Motivation",
  "Sinusitis",
  "Temper",
  "Mononucleosis",
  "Swollen ankle",
  "Asthma",
  "Mumps",
  "Sleepiness",
  "Magnesium tablets",
  "Magnesium",
  "Potassium",
  "Sodium",
  "Garlic",
  "Widow",
  "Building inspector",
  "Amnesia",
  "Testosterone",
  "Botanist",
  "Lupus",
  "Left tibia",
  "Steroids",
  "Headache",
  "Knife",
  "Knives",
  "Handwriting",
  "Low fat",
  "Low-fat diet",
  "Gallstones",
  "Gallbladder",
  "Self-catheterization",
  "Zika virus",
  "Clumps",
  "Irritated",
  "IV antibiotics",
  "Specialised message",
  "Compression socks",
  "Swelling up",
  "Fever",
  "Heavy lifting",
  "Liposuction",
  "Croup",
  "Fell",
  "Steady",
  "Glue ear",
  "Agitated",
  "Ammonia",
  "Vomiting",
  "Malarone tablets",
  "Broken ribs",
  "Heartbeat",
  "Anger",
  "Perfumes",
  "Pink eye",
  "Bump his head",
  "Bumps",
  "Memory",
  "Tonic-clonic",
  "Partial seizure",
  "Paracetamol",
  "Beta blocker",
  "Concussion",
  "Glandular fever",
  "Pulmonary embolism",
  "Joints pain",
  "VNS therapy",
  "Many strokes",
  "Freeze",
  "Dribbling",
  "Convulsions",
  "Blood clots",
  "Financial advisor",
  "Frontal lobe",
  "Seizures",
  "Meniere's disease",
  "Loss of hearing",
  "Social gathering",
  "Propranolol",
  "Tetanus",
  "Mouth ulcer",
  "Canker sores",
  "16mg",
  "Vision",
  "Lunchtime",
  "Squat position",
  "Acute inflammation",
  "Anti-clockwise",
  "Crackling",
  "Patella",
  "Exercise straps",
  "Hamstring",
  "Stretching",
  "Urgency",
  "Knee",
  "Intense",
  "Femur",
  "Pins and needles",
  "Cold sores",
  "Heart murmur",
  "Cycling",
  "Nightmares",
  "Heat pads",
  "Engineering",
  "Lying flat position",
  "PPI (proton pump inhibitors)",
  "Kidney infection",
  "Sweating",
  "Jabbing",
  "Counselling",
  "Spasm",
  "Breathlessness",
  "Ibuprofen",
  "Perfume",
  "White crust",
  "Pink eyes",
  "Gastric bypass surgery",
  "Cold compression",
  "Above normal",
  "Dread",
  "Firefighter",
  "Heartburn",
  "Anxiety",
  "Tired",
  "Weightlifter",
  "Allergy test",
  "Dementia",
  "Training",
  "Swimming",
  "Soccer",
  "Alcohol",
  "Fibromyalgia",
  "Antispasmodic",
  "Disc prolapse",
  "Cracked",
  "Pancreatitis",
  "Antifungal",
  "Mechanic",
  "Sinus infection",
  "Ladder",
  "Rotator cuff",
  "Co-codamol",
  "Ice packs",
  "Bump on the head",
  "Complex partial",
  "Trance",
  "Dribble",
  "Weight",
  "Ribs",
  "Heparin injections",
  "Joint pain",
  "Vertigo",
  "Concussions",
  "Anti-inflammatory",
  "Corticosteroid injection",
  "Ethanol",
  "Carbohydrates",
  "Golf",
  "Neck",
  "Thyroid",
  "Steroid injection",
  "3 miscarriages",
  "C-reactive protein",
  "Ultrasound",
  "Arthritis",
  "Uterine cancer",
  "Uterine balloon",
  "Right shoulder",
  "Juvenile rheumatic arthritis",
  "Light bleeding",
  "Meningitis",
  "Saline drip",
  "Kidney stone",
  "Stiff",
  "Bloated",
  "Debilitating",
  "Colonoscopy",
  "Multivitamin",
  "Vitamin B12",
  "Gastric flu",
  "Fitful",
  "Barium enema",
  "Stomach ulcer",
  "Trembling",
  "Law",
  "Isolated",
  "Clouded",
  "Metallic",
  "Caffeine",
  "Cystoscopy",
  "High blood pressure",
  "Itching",
  "IBS",
  "Transplant",
  "Dark red",
  "Protein",
  "Big toe",
  "Joints",
  "Wrists",
  "Cut my food",
  "Concentration",
  "Physical activity",
  "Graded exercise therapy",
  "Counsellor",
  "Faint",
  "Sensitivity to light",
  "Underactive thyroid",
  "Contagious",
  "Antiseptic shampoo",
  "Irritated skin",
  "Dilantin",
  "Rhinocort nasal spray",
  "Mucofen",
  "Flurbiprofen",
  "Klonopin",
  "Rivaroxaban",
  "Mitomycin",
  "Flomax",
  "Advair diskus",
  "Celebrex",
  "Neurontin",
  "Cyclophosphamide",
  "Allopurinol",
  "Morphine",
  "Zolpidem",
  "Nitroglycerin",
  "Clopidogrel",
  "Keflex",
  "Atenolol",
  "Sodium bicarbonate",
  "Neoprene",
  "Cardizem",
  "Metoprolol",
  "Hydralazine",
  "Labetalol",
  "Levothyroxine",
  "Zyrtec",
  "Proscar",
  "Synthroid",
  "Motrin",
  "Avelox",
  "Codeine",
  "Chlordiazepoxide",
  "Clidinium",
  "Simvastatin",
  "Flagyl",
  "Daptomycin",
  "Primaxin",
  "Methadone",
  "Levaquin",
  "Floppy",
  "Tongue",
  "Earache",
  "Spasms",
  "Gums",
  "Exhaustion",
  "Breast cancer",
  "Hay fever",
  "Project manager",
  "Patches",
  "Antacid",
  "Craving",
  "Pus",
  "Hard",
  "Lighter",
  "New mouse",
  "Golf ball",
  "Restless legs syndrome",
  "Carpal tunnel syndrome",
  "Scar",
  "Aspiration",
  "Fish oil",
  "Zinc",
  "Humidity",
  "Pregnancy",
  "Gardener",
  "Fracture",
  "Cheese",
  "Drill",
  "Mood swing",
  "Constant pain",
  "Cricking",
  "Jewellery maker",
  "Burning sensation",
  "Prostate cancer",
  "Echocardiogram",
  "Fluid",
  "Salads",
  "Dialysis",
  "Itchy leg",
  "Dark red urine",
  "Verapamil",
  "Vegetarian diet",
  "Vegan",
  "Dietary",
  "Dietitian",
  "Tooth extraction",
  "Cauterisation",
  "Cardiologist",
  "Dry cough",
  "Respiratory infection",
  "Biopsy",
  "Laparoscopy",
  "Blood test",
  "Memory lapse",
  "Fidget",
  "Strengthening exercises",
  "Cellulitis",
  "Stumbling",
  "Aneurysm",
  "Sides of buttocks",
  "Seizure",
  "Dairy",
  "Diary",
  "Balance",
  "Bearable",
  "Beer",
  "Bear",
  "Bank manager",
  "Liver",
  "Cancer",
  "Eyes",
  "Firefighters",
  "Migraine",
  "Gluten",
  "ACE inhibitors",
  "Brown marks",
  "Rheumatology",
  "Big toe arthritis",
  "Baclofen",
  "High-impact sports",
  "Sugar",
  "Frightening",
  "Vibrating",
  "Restricted diet",
  "Gout",
  "Dermatology consultation",
  "Allergy",
  "Pruritus",
  "Hives",
  "Orange",
  "Lemonade",
  "Multiple organ failure",
  "Peritonitis",
  "Right thumb",
  "Stomach pain",
  "Hernia",
  "Ventilation",
  "Stoma",
  "Cholesterol",
  "Growing pain",
  "Flat mattress",
  "Coma",
  "Ventilator",
  "Abdominal pain",
  "Tonsil",
  "Withdrawn",
  "Limping",
  "Limb",
  "Shoulder",
  "Ankles",
  "Healthy",
  "Gall stones",
  "Muscles",
  "Accountant",
  "Sister",
  "Drive",
  "Aerobics",
  "Cold water",
  "Flight attendant",
  "Blood transfusion",
  "Perfumed",
  "Hydrated",
  "Emotional",
  "Skin is dry and flaky",
  "Diet free of gluten",
  "Blisters",
  "Bicycle",
  "Oily fish",
  "Throat infection",
  "Ketogenic",
  "Cataract",
  "Left thumb",
  "Flaky",
  "Drinking tea",
  "Water",
  "Drooping eyelid",
  "Peanut",
  "Active thyroid",
  "Security guard",
  "Nephrologist",
  "Neurologist",
  "High-fibre diet",
  "Kidney cancer",
  "Sciatica",
  "Kidney graft",
  "Canal",
  "Calves",
  "Two toes",
  "Abdomen",
  "Warehouse",
  "Piercing",
  "Botox",
  "Chest",
  "Badminton",
  "Blotchy",
  "Leathery skin",
  "Hips",
  "Weakness",
  "Energy",
  "Left thigh",
  "Longstanding",
  "Bandage",
  "Panic attack",
  "Hypertension",
  "Herbalist",
  "Guitar",
  "Hydrocortisone",
  "Smell",
  "Weightlifting",
  "Chest infection",
  "Obesity",
  "Left ventricle",
  "Stage 3",
  "Call centre",
  "Convenience diet",
  "Scuba diving",
  "Vascular dementia",
  "Leukaemia",
  "Fractured rib",
  "Ears",
  "Sinuses",
  "Management",
  "Scoliosis",
  "Breastfeeding",
  "Knees",
  "Absence seizures",
  "Rheumatoid fever",
  "Echo",
  "Stuttered",
  "Omega-3",
  "Hacking",
  "Whispering",
  "Dog trainer",
  "Lupus groin",
  "Hammer",
  "Web designer",
  "Chest tightness",
  "Stutter",
  "Jogging",
  "Rheumatic fever",
  "Left leg",
  "Blurring of vision",
  "Fast food",
  "Voice",
  "Astigmatism",
  "White",
  "Glue",
  "Oral antibiotics",
  "Mushrooms",
  "Sour taste",
  "Sore throat",
  "Warm compresses",
  "Dental assistant",
  "Rubella",
  "Salmonella",
  "Styes",
  "Melatonin",
  "Melanoma",
  "Tea tree oil",
  "Topical antibiotic",
  "Blinking",
  "Dandruff",
  "Regurgitation",
  "Computer",
  "Lunch",
  "Injections",
  "Bracing",
  "Jaundice",
  "June",
  "Muscle relaxant",
  "Prickling",
  "Knee replacement",
  "Humid",
  "Clumsy",
  "Dark",
  "Hepatitis",
  "Tai chi",
  "Refreshed",
  "Bilirubin",
  "Dreadful fatigue",
  "Cirrhosis",
  "Dehydrated",
  "Stabbing",
  "Restless at school",
  "Brain fog",
  "Dizziness",
  "Handshake",
  "Dark urine",
  "Slurred",
  "Continence",
  "Neighbours",
  "Savoury",
  "Diarrhoea",
  "Baggage handler",
  "Luggage",
  "Vitiligo",
  "Commercial artist",
  "Strength",
  "Laxatives",
  "Junk food",
  "Climbing stairs",
  "Jaw exercise",
  "Uric acid",
  "Osteoporosis",
  "Software designer",
  "Lifting weights",
  "Calcium",
  "Preventive measures",
  "Ulcerative colitis",
  "Gastric reflux",
  "Sprain",
  "Pressure",
  "Dental hygienist",
  "Gallstone",
  "Discolouration",
  "Environmental engineer",
  "Sprained ankle",
  "Dressing",
  "Temperature",
  "Tetanus vaccination",
  "Difficult",
  "Different",
  "Deficiency",
  "Awareness",
  "Sharp mind",
  "Surgery",
  "Osteomyelitis",
  "Nail",
  "Opioids",
  "Fainting",
  "Pelvic ultrasound",
  "Cramps",
  "Clots",
  "Child care assistant",
  "Retirement",
  "Dancing",
  "Cranberry supplement",
  "Blurring",
  "Dizzy",
  "Ankle",
  "Hopelessness",
  "Ovarian cysts",
  "Tingling sensation",
  "Rubbing ointment",
  "Tiger balm",
  "Unsteady",
  "Jet lag",
  "Toe",
  "Tarsal fracture",
  "Clammy",
  "Chest pain",
  "Throat cancer",
  "Ginseng",
  "Lethargy",
  "Triptan",
  "Imbalance",
  "Prediabetes",
  "Heavy",
  "Ferritin",
  "Amino acid",
  "Bold patches",
  "Anxiety attacks",
  "Hotel receptionist",
  "Poliovirus",
  "Thyroid function test",
  "Hormonal imbalance",
  "Bald patches",
  "Scabbing",
  "Scabies",
  "Beta blockers",
  "Right knee",
  "Bunion",
  "Type 1 diabetes",
  "Freelancer journalist",
  "Distorted",
  "Stationary life",
  "DM",
  "Trapped nerve",
  "Sedentary life",
  "Hip",
  "Grain",
  "Lump",
  "Big toes",
  "Kidney disease",
  "Chiropractor",
  "Rash",
  "Bending over",
  "Dairy products",
  "Intense burning",
  "A translator",
  "Playing squash",
  "Whiplash",
  "Mouse",
  "An accountant",
  "Appendicitis",
  "An underactive thyroid",
  "Pelvic congestion",
  "Mild fever",
  "Bone loss in jaw",
  "A web designer",
  "Epilepticus",
  "Whipple's disease",
  "Gastroenterology",
  "Involuntary",
  "Pepper",
  "Peppermint",
  "Cricket",
  "Tremor",
  "Uncomplicated pregnancy",
  "Reflexes",
  "Imitating",
  "Breakfast",
  "Rely on",
  "Exacerbate",
  "Housewife",
  "Work",
  "Patchy",
  "Steroid cream",
  "Inflammatory",
  "Inflammation",
  "Inflamed",
  "Exercise",
  "Stress",
  "Light",
  "Regular",
  "Uterine balloon therapy",
  "Preventative medicine",
  "Miscarriages",
  "High-impact sport",
  "A sprain",
  "Laser",
  "Traumatic",
  "Bad haemorrhage",
  "Bend it",
  "Brownish",
  "An ultrasound",
  "Appetite",
  "Shockwave surgery",
  "Reflux",
  "Boxing",
  "Homemaker",
  "Dull ache",
  "Food poisoning",
  "Workaholic",
  "Electric",
  "Shock",
  "Seafood",
  "Shower gel",
  "Alzheimer's",
  "Spotting",
  "Sitting down",
  "Needles",
  "Cervical cancer",
  "Spirometry",
  "Excessive exercise",
  "Oil paints",
  "Layout",
  "Clothes",
  "Walking frame",
  "Movement",
  "Climbing upstairs",
  "Heaviness",
  "Speaking",
  "Jaw",
  "Slow",
  "Wisdom teeth",
  "Beauty therapist",
  "Stairs",
  "Bronchitis",
  "Craft",
  "High-need baby",
  "Eyelids",
  "Vitamin B6",
  "Twin sister",
  "Cleft lip",
  "Grommet",
  "Mushroom",
  "Endometriosis",
  "Uncooperative",
  "Picky",
  "Behaviour",
  "Muscle tones",
  "Waking scheduled",
  "Judo",
  "Waved hand",
  "Arms",
  "Armpit",
  "Bipolar",
  "Sweat",
  "Biologist",
  "Blister",
  "Hockey",
  "Taste",
  "Elbow joint",
  "Both calves",
  "Backhand",
  "Systemic lupus",
  "Juvenile rheumatoid arthritis",
  "Blindness",
  "Warm compression",
  "Computer programmer",
  "Serious wrist fracture",
  "Sour",
  "Oral / topical antibiotics",
  "Whisper / whispering",
  "Repeat",
  "Rheumatoid arthritis / fever",
  "Constricted",
  "Repetitive nerve stimulation",
  "Oat",
  "Kidney stones",
  "Steroid tablet",
  "Plenty fluids",
  "Wrist joint",
  "Slurred speech",
  "Flu vaccine",
  "Chewing",
  "Thymus gland",
  "Badminton sport",
  "Double vision",
  "Achilles tendon",
  "Spitting",
  "Shoulder dystocia",
  "Preeclampsia",
  "Nursery",
  "Tummy ache",
  "Chest X-ray",
  "Topical antibiotics",
  "Tetanus vaccine",
  "Sharp brain",
  "Convenient foods",
  "Pain",
  "Stiffened",
  "Left ankle",
  "Standing up",
  "Growing pains",
  "Cortisone cream",
  "Left ventricular hypertrophy",
  "Absence seizure",
  "Convenience food",
  "Coughing fits",
  "2 toes",
  "Piercing headache",
  "Leathery",
  "Hip joint",
  "Bold patch",
  "Dengue fever",
  "Coordination",
  "Thyroid function",
  "Anxiety attack",
  "Urinating",
  "Blue limbs",
  "Vibration",
  "Short of breath",
  "Droopy",
  "Fitness",
  "Fibre diet",
  "Antidepressant",
  "Embolisation",
  "Peanut allergy",
  "Both knees",
  "Headaches",
  "Puberty",
  "Traffic noise",
  "Shellfish",
  "Floating",
  "Cheeks",
  "Web organiser",
  "Lung cancer",
  "Prostatic cancer",
  "Pacemaker",
  "Muscle",
  "Skin rash",
  "Driving instructor",
  "Mini stroke",
  "Housebound",
  "Sticky eyes",
  "Uncomfortable stomach",
  "Hip replacement",
  "Alternative therapy",
  "Dry",
  "Awful",
  "Gluten-free diet",
  "Hydration",
  "Upper limb",
  "Anaerobic",
  "Exam",
  "Multiple system failure",
  "Stomach ache",
  "Colostomy",
  "Losing weight",
  "Nosebleed",
  "Vegetables",
  "Cholecystectomy",
  "Typically",
  "Fingers",
  "Glaucoma",
  "Groggy",
  "Invasive",
  "Invitations",
  "Jobbing",
  "Gapping",
  "Kidney",
  "Lifting",
  "Loss of energy",
  "Malaria",
  "Malaria tablets",
  "Meals",
  "Launch",
  "Normal",
  "Off-colour",
  "Oil paint",
  "Opioid",
  "Optic disc",
  "Perception",
  "Pounding sound",
  "Prevention",
  "Psychological assessment",
  "Radiotherapy",
  "SLE (systemic lupus erythematosus)",
  "Salad",
  "Self-conscious",
  "Shadow",
  "Shooting",
  "Spots",
  "Steroid injections",
  "Superior aspect",
  "Tension headaches",
  "Thyroid disease",
  "Toys",
  "Twisting",
  "Attack",
  "Autoimmune",
  "Bouncing sounds",
  "Brain scan",
  "Cleaner"
];