window.OET_WORDS = [
  "waking",
  "engineering",
  "ethanol",
  "squat position",
  "bruising",
  "upper limb",
  "neck",
  "crusty mucus",
  "chills",
  "rheumatic fever",
  "four months",
  "appendicitis",
  "traumatic",
  "osteoporosis",
  "allergy test",
  "a ce inhibitors",
  "different",
  "aching",
  "urinalysis",
  "free",
  "high",
  "peanut",
  "hockey",
  "ammonia",
  "meniere's disease",
  "scarlet",
  "wheezing",
  "immune system",
  "cataract",
  "blotches",
  "heart murmur",
  "mild fever",
  "steroids",
  "strength",
  "sphincter",
  "astigmatism",
  "tummy ache",
  "dancing",
  "celebrex",
  "toe",
  "ginseng supplements",
  "radiotherapy",
  "right shoulder",
  "vibration",
  "dermatology consultation",
  "stiffness",
  "blurred vision",
  "hydrated",
  "dietitian",
  "vns therapy",
  "bump on the head",
  "melatonin",
  "soap",
  "pink eye",
  "earache",
  "relief",
  "skin rashes",
  "unsociable",
  "eating",
  "fatigue",
  "indigestion",
  "eclampsia",
  "constipation",
  "peppermint",
  "calf calves",
  "aerobics",
  "gentle exercise",
  "contiguous",
  "baggage handler",
  "finances",
  "sodium",
  "simvastatin",
  "kidney cancer",
  "swollen ankle",
  "anaesthetic medication",
  "migraine",
  "swollen tongue",
  "fat diet",
  "thyroid function",
  "backhand",
  "an underactive thyroid",
  "ankle",
  "blurred",
  "position",
  "poliovirus",
  "orange",
  "ferritin",
  "jabbing",
  "walking frame",
  "bad odour",
  "awareness",
  "law",
  "burning",
  "codeine",
  "sprain",
  "fainting",
  "bone loss in jaw",
  "congested vein",
  "topical antibiotic",
  "grain",
  "iron deficiency",
  "compartment syndrome",
  "baclofen",
  "lunch",
  "acute",
  "whiplash",
  "physiotherapy session",
  "syndrome",
  "hair",
  "aneurysm",
  "sciatica",
  "pink eyes",
  "colour",
  "lung",
  "type  diabetes",
  "impaction",
  "shingles",
  "primaxin",
  "obese",
  "cycling",
  "lifting weights",
  "chest infection",
  "bloating",
  "botox",
  "workaholic",
  "flu",
  "painkillers",
  "breast cancer",
  "cold water",
  "pounding sound",
  "left thigh",
  "gallstones",
  "cardizem",
  "muscles",
  "vegan",
  "droopy",
  "choking",
  "knees",
  "soccer",
  "firefighters",
  "respiratory infection",
  "agitated",
  "lifting",
  "cold sores",
  "expansion",
  "diabetes",
  "liver",
  "distance",
  "both knees",
  "mononucleosis",
  "patches",
  "gastroenterology",
  "neighbours",
  "stretching",
  "appendectomy",
  "ears",
  "hives",
  "gallbladder",
  "cheeks",
  "lung cancer",
  "adhesion",
  "stomach ache",
  "prevention",
  "free diet",
  "white",
  "sodium bicarbonate",
  "contagious",
  "vocabulary",
  "security guard",
  "leukaemia",
  "lying down",
  "asthma",
  "sprain ankle",
  "ulcerative colitis",
  "oral contraceptives",
  "heparin injection",
  "ibuprofen",
  "zolpidem",
  "continence",
  "cyclophosphamide",
  "exercise straps",
  "deep vein thrombosis",
  "cough",
  "ribcage",
  "fingers",
  "counsellor",
  "steroid injections",
  "toys",
  "scrotum",
  "prickling",
  "white crusts",
  "reflexes",
  "steady",
  "gout",
  "manager",
  "mouth ulcer",
  "breathlessness",
  "kidney infection",
  "sweat",
  "shower gels",
  "alzheimers",
  "lemonades",
  "urine retention",
  "dread",
  "slurred speech",
  "swelling up",
  "june",
  "swollen",
  "regurgitation",
  "hydration",
  "steroid cream",
  "of gluten",
  "muscle biopsy",
  "climbing stairs",
  "drill",
  "chiropractor",
  "handwriting",
  "urinating",
  "convenience food",
  "groin area",
  "night sweats",
  "throat infection",
  "psoriasis",
  "sailor",
  "bloodshot",
  "regular",
  "cranberry supplement",
  "opioids",
  "weakness",
  "nosebleeds",
  "cold compression",
  "gluten",
  "sister",
  "beer",
  "mechanic",
  "rheumatology",
  "engineer",
  "clumsy",
  "unsaturated fats",
  "pacemaker",
  "chest",
  "growing pain",
  "cracked",
  "drinking tea",
  "disorientation",
  "broken ribs",
  "gums",
  "sway",
  "sides of buttocks",
  "dizziness",
  "housewife",
  "chlordiazepoxide",
  "irritable bowel",
  "coconut oil",
  "yoghurt",
  "sharp",
  "pre",
  "brain scan",
  "garlic pills",
  "breastfeed",
  "speaking",
  "emotional outbursts",
  "awful",
  "coughing fits",
  "short of breath",
  "gastric bypass surgery",
  "serious wrist fracture",
  "systemic lupus",
  "sour",
  "mushroom",
  "lethargy",
  "fuzzy",
  "hepatitis",
  "potassium level",
  "beeswax",
  "bulimia",
  "message",
  "fitful",
  "limb",
  "flomax",
  "muscle relaxant",
  "left leg",
  "shoulder",
  "crutches",
  "withdrawn",
  "unsteady",
  "confidence",
  "kidney",
  "urinary tract infection",
  "mitomycin",
  "rib cage",
  "cricking",
  "tonic",
  "tired",
  "weight",
  "scuba diving",
  "sleep apnoea",
  "drained",
  "complication",
  "impact sports",
  "cry",
  "angina",
  "oil paints",
  "injection",
  "plenty",
  "strangulation",
  "left tibia",
  "mini stroke",
  "meals",
  "accountant",
  "anaerobic",
  "bunion",
  "stoma",
  "muscle tones",
  "gastric",
  "meat",
  "cervical cancer",
  "gymnastics",
  "knee",
  "translator",
  "repeat",
  "metal rod",
  "disease",
  "fertility",
  "pus",
  "life",
  "healthy",
  "social gathering",
  "chef",
  "muscle",
  "invitations",
  "freelancer journalist",
  "software designer",
  "hot pads",
  "assessment",
  "vitiligo",
  "vibrating",
  "allopurinol",
  "ankles",
  "joints pain",
  "cardiologist",
  "active thyroid",
  "colouring",
  "trance",
  "big toes",
  "pruritus",
  "greasy",
  "two toes",
  "drooping eyelid",
  "tiger balm",
  "lupus",
  "stabbing",
  "loss of hearing",
  "yoga",
  "hay fever",
  "biopsy",
  "skin",
  "computer programmer",
  "overactive thyroid",
  "lupus groin",
  "pelvic congestion",
  "rheumatoid arthritis  fever",
  "constant pain",
  "teething",
  "multiple sclerosis",
  "dressing",
  "diary",
  "whisper  whispering",
  "blister",
  "antacid",
  "many strokes",
  "organiser",
  "vitamin b",
  "autoimmune",
  "jaw exercise",
  "rotator cuff",
  "longstanding",
  "shooting",
  "bladder",
  "bloated",
  "social gatherings",
  "ginseng",
  "itchy",
  "k eflex",
  "saline drip",
  "urethral dilation",
  "dry",
  "programmer",
  "anxiety",
  "agoraphobia",
  "stiff",
  "washing hair",
  "throbbing",
  "acoustic neuroma",
  "shockwave",
  "a velox",
  "dry cough",
  "paralysis",
  "seizure",
  "dizzy",
  "fractured",
  "japan",
  "osteomyelitis",
  "convenience diet",
  "salmonella",
  "frozen egg",
  "tie",
  "patchy",
  "fluids",
  "salad",
  "deodorant",
  "flight attendant",
  "headache",
  "clouded",
  "nursery",
  "some sort of food",
  "fever",
  "fidget",
  "change dressing",
  "dribbling",
  "intermittent",
  "shadow",
  "need baby",
  "left ventricular hypertrophy",
  "jaundice",
  "concussions",
  "eyelids",
  "a web designer",
  "cirrhosis",
  "wrist joint",
  "debilitating",
  "neurologist",
  "badminton sport",
  "stomach cramps",
  "chewing",
  "eye drops",
  "hiking",
  "nasal spray",
  "counselling",
  "elbow joint",
  "sensitivity to light",
  "zika virus",
  "breastfeeding",
  "stinging",
  "sick and dizzy",
  "neighbour",
  "spitting",
  "office",
  "prostatic cancer",
  "swallow",
  "discolouration",
  "big toe arthritis",
  "anti",
  "junk food",
  "amnesia",
  "puberty",
  "bronchitis",
  "skin is dry and flaky",
  "crowded places",
  "lunch time",
  "anxiety attack",
  "heaviness",
  "complex partial",
  "aerobic exercises",
  "grommet",
  "preventive measures",
  "exacerbate",
  "scabbing",
  "yoga class",
  "hips",
  "shock",
  "intermittent catheter",
  "light bleeding",
  "central nervous system",
  "deficiency",
  "daptomycin",
  "biologist",
  "mucofen",
  "heartbeat",
  "heavy lifting",
  "dribble",
  "levothyroxine",
  "injections",
  "construction worker",
  "meningitis",
  "allergy",
  "driving",
  "sepsis",
  "varicose veins",
  "chins",
  "affection",
  "preventer",
  "a translator",
  "badminton",
  "partial seizure",
  "chest x",
  "drowsy",
  "tonsillectomy",
  "nephrologist",
  "isolated",
  "oil paint",
  "shellfish",
  "whipple's disease",
  "scalp",
  "bend it",
  "alzheimer's",
  "left buttock",
  "hard",
  "calamine lotion",
  "cramps",
  "infertile",
  "popping sound",
  "ladder",
  "slow",
  "kidney disease",
  "hernia",
  "restless legs syndrome",
  "shoulders",
  "rely on",
  "involuntary",
  "cut my food",
  "lying flat",
  "in concentration",
  "uterine cancer",
  "sweating",
  "iron deficiency anaemia",
  "tumour markers",
  "stress",
  "cholesterol",
  "perception",
  "cortisone",
  "zinc",
  "intense burning",
  "b deficiency",
  "exhaustion",
  "surgery",
  "pneumonia",
  "knives",
  "seizures",
  "bold patch",
  "concussion",
  "journalist",
  "wrist",
  "bouts of vomiting",
  "massage therapist",
  "bold",
  "hip replacement",
  "swelling",
  "anger",
  "blood test",
  "shivering",
  "mumps",
  "thyroid disease",
  "sugar",
  "transplant",
  "tendon",
  "faint",
  "tea",
  "suprapubic catheter",
  "administrator",
  "bipolar",
  "confusion",
  "knee replacement",
  "hamstring",
  "difficult",
  "dark red urine",
  "z yrtec",
  "concentrate",
  "vascular",
  "warm compresses",
  "vomited",
  "ultrasound",
  "abdominal area",
  "new mouse",
  "steroid",
  "stomach ulcer",
  "styes",
  "exam",
  "restless",
  "blotchy",
  "dairy products",
  "convulsions",
  "burping",
  "absence seizures",
  "tension headaches",
  "big toe",
  "thumb",
  "nosebleed",
  "magazine editor",
  "bruise",
  "hammer",
  "malaria",
  "growing pains",
  "lemonade",
  "fluid",
  "savoury snacks",
  "cystitis",
  "spasms",
  "topical antibiotics",
  "rhinocort nasal spray",
  "bad haemorrhage",
  "jewellery maker",
  "underactive thyroid",
  "distorted",
  "drive",
  "absence seizure",
  "stiffened",
  "levaquin",
  "liposuction",
  "canal",
  "blurring",
  "golf",
  "cricket",
  "malaria tablets",
  "iv antibiotics",
  "attack",
  "behaviour",
  "tetanus",
  "clingy",
  "panic",
  "magnesium tablets",
  "knife",
  "bereavement",
  "mouth ulcers",
  "scar",
  "work",
  "imbalance",
  "environmental engineering",
  "antifungal",
  "events manager",
  "carpenter",
  "radiation",
  "losing weight",
  "white crust",
  "needles",
  "personal trainer",
  "juvenile rheumatoid arthritis",
  "uric acid",
  "building inspector",
  "bruises",
  "co",
  "blindness",
  "leathery",
  "menstruation",
  "ibs",
  "cystoscopy",
  "motivation",
  "physiotherapy",
  "wisdom teeth",
  "hydralazine",
  "jaw",
  "calcium",
  "sleepiness",
  "exercise",
  "swallowing",
  "imitating",
  "acupuncture",
  "fibre diet",
  "probiotic",
  "uterine balloon therapy",
  "shoulder dystocia",
  "achilles tendon",
  "piercing",
  "cauterisation",
  "tinnitus",
  "luggage",
  "tantrum",
  "tetanus vaccination",
  "catheterization",
  "baggage",
  "alcohol",
  "dog trainer",
  "homemaker",
  "graded",
  "threatening",
  "lunchtime",
  "coma",
  "hand cream",
  "financial advisor",
  "juvenile rheumatic arthritis",
  "dilantin",
  "dark red",
  "shooting sensation",
  "mood swing",
  "fertility treatment",
  "neurontin",
  "colonoscopy",
  "cut two fingers",
  "blurring of vision",
  "urgency",
  "judo",
  "irritated",
  "cleaner",
  "stage",
  "balance",
  "pleurisy",
  "antisocial",
  "appetite",
  "diet free",
  "collarbone",
  "bald",
  "restless at school",
  "palpitations",
  "sinusitis",
  "uncooperative",
  "oily fish",
  "triptan",
  "nail",
  "prediabetes",
  "fell",
  "scoliosis",
  "ketogenic",
  "superior aspect",
  "left ankle",
  "barium enema",
  "dust",
  "beta blockers",
  "perfumes",
  "bank manager",
  "seafood",
  "blood thinners",
  "endometriosis",
  "menopause",
  "light",
  "heel",
  "pregnancy",
  "fast food",
  "standing up",
  "impact sport",
  "armpit",
  "lighter",
  "tonsillitis",
  "reactive protein",
  "garlic",
  "brownish",
  "limping",
  "physical activity",
  "voice",
  "corticosteroids",
  "sle systemic lupus erythematosus",
  "mouth",
  "market research",
  "gallstone",
  "waved hand",
  "febrile convulsion",
  "antispasmodic",
  "methadone",
  "dialysis",
  "playing squash",
  "bearable",
  "nausea",
  "fibromyalgia",
  "malarone tablets",
  "blood",
  "tennis ball",
  "food poisoning",
  "clothes",
  "bump his head",
  "dementia",
  "groin",
  "carbohydrates",
  "double vision",
  "abdominal pain",
  "senna tablets",
  "protein",
  "vitamin d",
  "widow",
  "cream",
  "off",
  "chi",
  "firefighter",
  "cracked lips",
  "clammy",
  "brain fog",
  "echocardiogram",
  "spasm",
  "multiple organ failure",
  "died",
  "obesity",
  "oat",
  "numbness",
  "humidity",
  "osteoarthritis",
  "left calf",
  "electric",
  "lymph nodes",
  "stumbling",
  "project manager",
  "ointment",
  "laparoscopy",
  "lower back",
  "layout",
  "weightlifting",
  "botanist",
  "distracted",
  "s ynthroid",
  "bicycle",
  "croup",
  "laser",
  "nitroglycerin",
  "compression socks",
  "antihistamines",
  "smell",
  "nightmares",
  "fingertips",
  "amino acid",
  "an ultrasound",
  "dental assistant",
  "ear infection",
  "tailor",
  "trembling",
  "housebound",
  "brown marks",
  "lump",
  "inflammatory",
  "oral  topical antibiotics",
  "sharp mind",
  "thirsty",
  "coordination",
  "vascular dementia",
  "training",
  "left",
  "atrial fibrillation",
  "ice packs",
  "bracing",
  "convenient foods",
  "multiple system failure",
  "red spots",
  "mouse",
  "freeze",
  "bending over",
  "opioid",
  "prostate cancer",
  "booster",
  "cholecystectomy",
  "groggy",
  "sticky eyes",
  "heartburn",
  "ppi",
  "restricted diet",
  "blood transfusion",
  "pancreatitis",
  "dairy",
  "sales",
  "crackling",
  "glaucoma",
  "morphine",
  "judge",
  "tea tree oil",
  "environmental engineer",
  "dental hygienist",
  "ventilation",
  "asking",
  "lethargic",
  "wrists",
  "thyroid",
  "tightness",
  "laxatives",
  "fracture",
  "smoking",
  "vomiting",
  "conscious",
  "call centre",
  "energy",
  "down syndrome",
  "twisting",
  "chickenpox",
  "clockwise",
  "holter monitor",
  "whiplash injury",
  "temperature",
  "scabies",
  "autism",
  "frightening",
  "boxing",
  "loss of energy",
  "flat position",
  "cold compress",
  "antiseptic shampoo",
  "peanut allergy",
  "financial difficulties",
  "ovarian cysts",
  "dizzy spells",
  "epilepsy",
  "memory lapse",
  "indoor exercises",
  "balloon",
  "hotel receptionist",
  "exercise therapy",
  "popping",
  "climbing upstairs",
  "darker",
  "magnesium",
  "sinuses",
  "thymus gland",
  "tonsil",
  "chubby",
  "uncomplicated pregnancy",
  "clumps",
  "specialised",
  "flat mattress",
  "stomach",
  "herbalist",
  "muscle dystrophy",
  "bouncing sounds",
  "high blood pressure",
  "picky",
  "flaky",
  "floppy",
  "colostomy",
  "savoury",
  "kidney stone",
  "loss",
  "spirometry",
  "itchy leg",
  "water",
  "incontinence",
  "red meat",
  "joints",
  "hip joint",
  "rivaroxaban",
  "caffeine",
  "dancing instructor",
  "pelvic ultrasound",
  "bandage",
  "cellulitis",
  "refreshed",
  "spots",
  "beauty therapist",
  "perfume",
  "motrin",
  "uncomfortable stomach",
  "dreadful fatigue",
  "hormonal imbalance",
  "herbal oil",
  "craving",
  "alternative therapy",
  "cloudy",
  "anaemia",
  "tremor",
  "dengue fever",
  "oranges",
  "gall stones",
  "sinus inflammation",
  "sprained",
  "visual perception",
  "dm",
  "skin rash",
  "salads",
  "irritable",
  "bilirubin",
  "oral antibiotics",
  "hacking",
  "lawyer",
  "self",
  "blisters",
  "surveyor",
  "knife and fork",
  "kidney graft",
  "rheumatoid fever",
  "left thumb",
  "arthritis",
  "mushrooms",
  "codamol",
  "advair diskus",
  "patella",
  "eczema",
  "pain",
  "warm compression",
  "fitness",
  "trapped nerve",
  "heat packs",
  "hypertension",
  "sensation",
  "dyspepsia",
  "metallic",
  "metoprolol",
  "right thumb",
  "scheduled",
  "inflammation",
  "hearing loss",
  "pressure",
  "dietary",
  "pulmonary embolism",
  "excessive exercise",
  "ablation",
  "sticky",
  "both calves",
  "carpal tunnel syndrome",
  "sharp brain",
  "v erapamil",
  "rubella",
  "management",
  "strawberry tongue",
  "tooth extraction",
  "flu vaccine",
  "labetalol",
  "canker sores",
  "rib",
  "presentation",
  "dehydrated",
  "aspiration",
  "golf ball",
  "bent",
  "vision",
  "breech",
  "diarrhoea",
  "ventilator",
  "full blood count",
  "eyes",
  "pulsing",
  "glandular fever",
  "flagyl",
  "preventative medicine",
  "frontal lobe",
  "heparin injections",
  "peritonitis",
  "gapping",
  "testosterone",
  "strengthening exercises",
  "throat cancer",
  "humid",
  "ribs",
  "preeclampsia",
  "headaches",
  "software developer",
  "hydrocortisone",
  "heartbeats",
  "bitter taste",
  "bear",
  "vegetables",
  "breakfast",
  "sore throat",
  "joint pain",
  "clopidogrel",
  "graphic designer",
  "mg",
  "constricted",
  "migraines",
  "pressure sores",
  "web designer",
  "reflux",
  "wedding",
  "paracetamol",
  "dark",
  "memory",
  "tarsal fracture",
  "invasive",
  "above normal",
  "spider",
  "thighs",
  "epilepticus",
  "miscarriages",
  "watery",
  "neoprene",
  "right knee",
  "cancer",
  "glue ear",
  "jobbing",
  "toes",
  "slurred",
  "concentration",
  "back",
  "pepper",
  "heavy",
  "tomatoes",
  "flurbiprofen",
  "depression",
  "pituitary",
  "oesophageal cancer",
  "guitar",
  "tai",
  "klonopin",
  "sour taste",
  "itching",
  "traffic noise",
  "rubbing ointment",
  "stairs",
  "craft",
  "optic disc",
  "punctured lung",
  "fine",
  "dull ache",
  "deafness",
  "chest pain",
  "antihistamine",
  "clonic",
  "intense",
  "clots",
  "embolisation",
  "jogging",
  "basketball",
  "pins and needles",
  "gastric bypass",
  "child care assistant",
  "emotional",
  "breathless",
  "floating",
  "disc prolapse",
  "computer",
  "vertigo",
  "swimming",
  "vegetarian diet",
  "proscar",
  "van driver",
  "stutter",
  "clicking",
  "calves",
  "chemotherapy",
  "building sites",
  "commercial artist",
  "taste",
  "eyebrows",
  "vaccine",
  "rash",
  "blinking",
  "infection",
  "ventricle",
  "car accident",
  "stroke",
  "omega",
  "jet lag",
  "low fat",
  "whispering",
  "driving instructor",
  "multivitamin",
  "abdomen",
  "stuttered",
  "stationary life",
  "corticosteroid injection",
  "web",
  "twin sister",
  "typically",
  "goalkeeper",
  "weightlifter",
  "speech impairment",
  "dandruff",
  "potassium",
  "fish oil",
  "antidepressant",
  "propranolol",
  "university lecturer",
  "uterine",
  "launch",
  "constricted veins",
  "low",
  "dragging",
  "sitting down",
  "handshake",
  "kidney stones",
  "tingling",
  "heat pads",
  "cleft lip",
  "melanoma",
  "gardener",
  "blue limbs",
  "beta blocker",
  "ppi proton pump inhibitors",
  "temper",
  "atenolol",
  "sinus infection",
  "femur",
  "clidinium",
  "anxiety attacks",
  "steroid tablet",
  "perfumed",
  "bumps",
  "hip",
  "jump",
  "shower gel",
  "cheese",
  "arms",
  "dark urine",
  "movement",
  "inflamed",
  "normal",
  "tongue",
  "financial problems",
  "rods",
  "glue",
  "botox injection",
  "gain",
  "hopelessness",
  "gastric flu",
  "panic attacks",
  "ray",
  "psychological",
  "leathery skin",
  "steroid injection",
  "repetitive nerve stimulation",
  "vegetarian",
  "thyroid function test",
  "rugby",
  "insomnia",
  "retirement",
  "spotting",
  "anxious",
  "an accountant",
  "sedentary life",
  "wrist brace",
  "warehouse",
  "whooping",
  "echo"
];
